package com.mameen.isomessage.emv

import kotlin.random.Random

/**
 * DE55 Builder — Fake EMV Data Generator (Educational)
 *
 * DE55 in ISO8583 carries the EMV chip data in TLV format.
 * This builder creates FAKE but structurally correct EMV data for simulation.
 *
 * ⚠️ IMPORTANT: This generates demo data ONLY.
 * Real EMV cryptograms are generated by the card's secure element using
 * a derived key and cannot be faked without the card's master key.
 * Real EMV processing requires Visa/Mastercard EMV kernel certification.
 *
 * Purpose:
 * - Demonstrate DE55 structure for educational purposes
 * - Test ISO8583 parsing code with realistic data
 * - Portfolio/demo application use only
 */
object De55Builder {

    /**
     * Generate a fake DE55 hex string with realistic EMV TLV structure.
     * All cryptographic values are randomly generated and NOT cryptographically valid.
     */
    fun buildFakeDe55(
        amount: Long = 1000L,
        currencyCode: String = "0818",
        countryCode: String = "0818",
        transactionType: String = "00"
    ): String {
        val tlvObjects = listOf(
            // 9F26 — ARQC (Application Request Cryptogram)
            // In real EMV: generated by card using 3DES/AES with derived session key
            // Here: random 8 bytes (purely fake)
            TlvObject(
                tagHex = "9F26",
                length = 8,
                valueHex = randomHex(8),
                knownTag = EmvTag.ARQC
            ),
            // 9F27 — Cryptogram Information Data (CID)
            // 80 = ARQC (online authorisation cryptogram)
            // 40 = TC (Transaction Certificate — issuer approved offline)
            // 00 = AAC (Application Authentication Cryptogram — declined offline)
            TlvObject(
                tagHex = "9F27",
                length = 1,
                valueHex = "80",  // ARQC — going online
                knownTag = null
            ),
            // 9F10 — Issuer Application Data
            TlvObject(
                tagHex = "9F10",
                length = 7,
                valueHex = "07A0000002541010",
                knownTag = EmvTag.IAD
            ),
            // 9F37 — Unpredictable Number (terminal-generated random nonce)
            TlvObject(
                tagHex = "9F37",
                length = 4,
                valueHex = randomHex(4),
                knownTag = EmvTag.UNPREDICTABLE_NUMBER
            ),
            // 9F36 — Application Transaction Counter
            TlvObject(
                tagHex = "9F36",
                length = 2,
                valueHex = "%04X".format(Random.nextInt(1, 9999)),
                knownTag = EmvTag.ATC
            ),
            // 95 — Terminal Verification Results
            // 0000000000 = All checks passed (no issues)
            TlvObject(
                tagHex = "95",
                length = 5,
                valueHex = "0000000000",
                knownTag = EmvTag.TVR
            ),
            // 9A — Transaction Date (YYMMDD)
            TlvObject(
                tagHex = "9A",
                length = 3,
                valueHex = currentDateBcd(),
                knownTag = EmvTag.TRANSACTION_DATE
            ),
            // 9C — Transaction Type
            TlvObject(
                tagHex = "9C",
                length = 1,
                valueHex = transactionType,
                knownTag = EmvTag.TRANSACTION_TYPE
            ),
            // 9F02 — Amount, Authorised (BCD, 6 bytes = 12 digits)
            TlvObject(
                tagHex = "9F02",
                length = 6,
                valueHex = amount.toString().padStart(12, '0'),
                knownTag = EmvTag.AMOUNT_AUTHORISED
            ),
            // 5F2A — Transaction Currency Code
            TlvObject(
                tagHex = "5F2A",
                length = 2,
                valueHex = currencyCode,
                knownTag = EmvTag.TRANSACTION_CURRENCY
            ),
            // 82 — Application Interchange Profile
            // 1800 = Offline data auth supported, Online PIN supported
            TlvObject(
                tagHex = "82",
                length = 2,
                valueHex = "1800",
                knownTag = EmvTag.AIP
            ),
            // 9F34 — CVM Results (Cardholder Verification Method)
            // 420302 = Online PIN, always, succeeded
            TlvObject(
                tagHex = "9F34",
                length = 3,
                valueHex = "420302",
                knownTag = EmvTag.CVM_RESULTS
            ),
            // 9F33 — Terminal Capabilities
            TlvObject(
                tagHex = "9F33",
                length = 3,
                valueHex = "E0F8C8",
                knownTag = EmvTag.TERMINAL_CAPABILITIES
            ),
            // 9F1A — Terminal Country Code
            TlvObject(
                tagHex = "9F1A",
                length = 2,
                valueHex = countryCode,
                knownTag = EmvTag.TERMINAL_COUNTRY
            ),
            // 9F35 — Terminal Type
            TlvObject(
                tagHex = "9F35",
                length = 1,
                valueHex = "22",  // Attended, online-only
                knownTag = EmvTag.TERMINAL_TYPE
            ),
            // 9B — Transaction Status Information
            TlvObject(
                tagHex = "9B",
                length = 2,
                valueHex = "E800",
                knownTag = EmvTag.TSI
            )
        )

        return TlvParser.encode(tlvObjects)
    }

    /**
     * Generate a "contactless" DE55 with NFC-specific tags.
     */
    fun buildFakeContactlessDe55(amount: Long = 500L): String {
        // Contactless transactions typically have a smaller set of TLV objects
        val tlvObjects = listOf(
            TlvObject("9F26", 8, randomHex(8), EmvTag.ARQC),
            TlvObject("9F27", 1, "80", null),
            TlvObject("9F10", 7, "07A0000002541010", EmvTag.IAD),
            TlvObject("9F37", 4, randomHex(4), EmvTag.UNPREDICTABLE_NUMBER),
            TlvObject("9F36", 2, "%04X".format(Random.nextInt(1, 9999)), EmvTag.ATC),
            TlvObject("95", 5, "0000000000", EmvTag.TVR),
            TlvObject("9A", 3, currentDateBcd(), EmvTag.TRANSACTION_DATE),
            TlvObject("9C", 1, "00", EmvTag.TRANSACTION_TYPE),
            TlvObject("9F02", 6, amount.toString().padStart(12, '0'), EmvTag.AMOUNT_AUTHORISED),
            // 9F6D — Contactless specific: MSD/VSDC indicator
            TlvObject("9F6D", 1, "20", null)
        )
        return TlvParser.encode(tlvObjects)
    }

    private fun randomHex(bytes: Int): String =
        (0 until bytes).joinToString("") { "%02X".format(Random.nextInt(256)) }

    private fun currentDateBcd(): String {
        val cal = java.util.Calendar.getInstance()
        return "%02d%02d%02d".format(
            cal.get(java.util.Calendar.YEAR) % 100,
            cal.get(java.util.Calendar.MONTH) + 1,
            cal.get(java.util.Calendar.DAY_OF_MONTH)
        )
    }
}
