package com.mameen.isomessage.emv

/**
 * EMV Tag definitions
 *
 * EMV (Europay, Mastercard, Visa) uses a TLV (Tag-Length-Value) encoding
 * for chip card communication. Every piece of data has a tag, a length, and a value.
 *
 * Tags are defined in the EMV specification Book 3.
 * Understanding these tags is essential for anyone working in payment systems.
 *
 * The entire DE55 field in ISO8583 is a concatenation of TLV objects.
 */
enum class EmvTag(
    val tagHex: String,
    val displayName: String,
    val description: String,
    val isConstructed: Boolean = false
) {
    // ── Application Data ──────────────────────────────────────────────────────
    AID("4F", "Application Identifier",
        "Identifies the payment application on the chip (e.g., Visa Credit = A0000000031010). " +
                "The terminal reads this to know which kernel/spec to follow."),

    APP_LABEL("50", "Application Label",
        "Human-readable name of the application, e.g. 'VISA CREDIT' or 'MASTERCARD'."),

    TRACK2_EQUIVALENT("57", "Track 2 Equivalent Data",
        "Chip-equivalent of magnetic stripe Track 2. Contains PAN and expiry. " +
                "NEVER store this — same PCI DSS restrictions as physical Track 2."),

    PAN("5A", "Application PAN",
        "Primary Account Number stored on chip. Same as DE2 in ISO8583."),

    APP_EXPIRY("5F24", "Application Expiry Date",
        "Card expiry date in YYMMDD format. Example: 261231 = December 31, 2026."),

    // ── Cardholder Data ───────────────────────────────────────────────────────
    CARDHOLDER_NAME("5F20", "Cardholder Name",
        "Name as printed on the card. Used in receipt generation. " +
                "May be blank on contactless-only cards."),

    // ── Transaction Context ───────────────────────────────────────────────────
    AMOUNT_AUTHORISED("9F02", "Amount, Authorised",
        "The authorisation amount in minor currency units, BCD-encoded. " +
                "This is the same value as DE4 in ISO8583."),

    AMOUNT_OTHER("9F03", "Amount, Other",
        "Cashback amount (if any). Zero for standard purchase transactions."),

    TRANSACTION_DATE("9A", "Transaction Date",
        "Date the transaction was initiated, YYMMDD format."),

    TRANSACTION_TIME("9F21", "Transaction Time",
        "Time the transaction was initiated, HHmmss format."),

    TRANSACTION_TYPE("9C", "Transaction Type",
        "Type of financial transaction: 00=Purchase, 20=Refund, 09=Cash Advance."),

    TRANSACTION_CURRENCY("5F2A", "Transaction Currency Code",
        "ISO 4217 numeric currency code. Same as DE49 in ISO8583."),

    // ── Terminal Data ─────────────────────────────────────────────────────────
    TERMINAL_COUNTRY("9F1A", "Terminal Country Code",
        "ISO 3166 numeric country code where the terminal is located. " +
                "818 = Egypt. Used for domestic vs. international transaction routing."),

    TERMINAL_CAPABILITIES("9F33", "Terminal Capabilities",
        "Byte flags describing what the terminal can do: " +
                "manual key entry, magnetic stripe, chip, offline PIN, online PIN, etc."),

    TERMINAL_TYPE("9F35", "Terminal Type",
        "Indicates if terminal is attended/unattended, online/offline capable. " +
                "22 = Attended, online-only terminal (typical POS)."),

    TVR("95", "Terminal Verification Results",
        "5-byte bitmap from the terminal, indicating the outcome of each EMV check. " +
                "If any bit is 1, something went wrong (expired card, offline PIN failed, etc.). " +
                "The terminal decides whether to proceed online or decline offline."),

    TSI("9B", "Transaction Status Information",
        "2-byte bitmap from the card, indicating which functions were performed. " +
                "Bit 7 = Offline data authentication performed, Bit 6 = Cardholder verification performed, etc."),

    // ── Cryptography (The Core of EMV Security) ───────────────────────────────
    ARQC("9F26", "Application Request Cryptogram (ARQC)",
        "THE most important EMV tag! This 8-byte cryptogram is generated by the card's secure element " +
                "using a key derived from the card's master key and the transaction data. " +
                "The issuer validates this in real-time to prove a genuine card was present. " +
                "Prevents counterfeit card fraud that was rampant with magnetic stripe."),

    ATC("9F36", "Application Transaction Counter",
        "A sequential counter incremented by the card for every transaction. " +
                "The issuer checks this to detect replayed or out-of-order transactions. " +
                "If ATC is lower than the last seen ATC, the transaction may be a replay attack."),

    IAD("9F10", "Issuer Application Data",
        "Issuer-specific data included in the cryptogram calculation. " +
                "Contains the Cryptogram Version Number (CVN) which tells the issuer " +
                "which algorithm was used to generate the ARQC."),

    UNPREDICTABLE_NUMBER("9F37", "Unpredictable Number",
        "4-byte random number generated by the terminal, included in the ARQC calculation. " +
                "This prevents replay attacks — each transaction has a unique random nonce."),

    // ── Cardholder Verification ───────────────────────────────────────────────
    CVM_RESULTS("9F34", "Cardholder Verification Method Results",
        "Result of cardholder verification: PIN (online/offline), signature, or no CVM. " +
                "3 bytes: [CVM performed][CVM condition][result]. " +
                "Example: 420302 = Online PIN, succeeds."),

    // ── Risk Management ───────────────────────────────────────────────────────
    AIP("82", "Application Interchange Profile",
        "2-byte bitmap from the card indicating its capabilities: " +
                "offline data authentication, cardholder verification, terminal risk management, etc."),

    AFL("94", "Application File Locator",
        "List of records on the card to be read. " +
                "The terminal reads each record to get card data needed for the transaction.");

    val tagBytes: ByteArray
        get() = tagHex.chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    val isMultiByte: Boolean get() = tagHex.length > 2

    companion object {
        fun fromHex(hex: String): EmvTag? =
            entries.find { it.tagHex.equals(hex, ignoreCase = true) }
    }
}
